name: hello-world
on: [push]
jobs:
  greetings:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello world"
      - run: ls -la
      - run: apt-get update && apt-get install cowsay
      - run: /usr/games/cowsay -f /usr/share/cowsay/cows/turtle.cow hello
