name: hello-world
on: [push]
jobs:
  greetings:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello world"
      - run: ls -la
      - run: sudo apt-get update && sudo apt-get install -y cowsay
      - run: /usr/games/cowsay -f /usr/share/cowsay/cows/turtle.cow hello

  check-bats-version:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
